[package]
name = "user_profile_nft"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }

[dev-dependencies]
snforge_std = "0.47.0"

[[target.starknet-contract]]
sierra = true
casm = true
